# Generated by Django 5.0.4 on 2024-04-30 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("default_location", models.CharField(blank=True, max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="dashboard.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SKU", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units", models.CharField(max_length=20)),
                ("minimum_stock", models.IntegerField(default=0)),
                ("desired_stock", models.IntegerField(default=0)),
                ("is_assembly", models.BooleanField(default=False)),
                ("is_component", models.BooleanField(default=False)),
                ("is_purchaseable", models.BooleanField(default=True)),
                ("is_salable", models.BooleanField(default=True)),
                ("is_bundle", models.BooleanField(default=False)),
                ("is_trackable", models.BooleanField(default=True)),
                ("in_stock", models.IntegerField(default=0)),
                ("total_allocated", models.IntegerField(default=0)),
                ("allocated_to_builds", models.IntegerField(default=0)),
                ("allocated_to_sales", models.IntegerField(default=0)),
                ("available_stock", models.IntegerField(default=0)),
                ("incoming_stock", models.IntegerField(default=0)),
                ("on_build_order", models.IntegerField(default=0)),
                ("net_stock", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="dashboard.category",
                    ),
                ),
            ],
        ),
    ]
