# Generated by Django 5.0.4 on 2024-05-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_passwordresetcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.AddField(
            model_name="item",
            name="default_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="external_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="variant_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="dashboard.item",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="default_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="SKU",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="dashboard.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="units",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
