# Generated by Django 5.0.4 on 2024-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_item_tags_item_default_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
