# Generated by Django 5.0.4 on 2024-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="SKU",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
